print("what is the name of the gift giver?")
name = raw_raw_input()
print("what is the present they gave you?")
present = raw_raw_input()
print("how old where u on your birthday?")
age = int(raw_raw_input())
print("what is u r name?")
yourname = raw_raw_input()
print("dear" +  name  + ",")
print("")
print("thank you for the" + '  ' + present + ".")
print("i really like it.I can't believe")
print("i am already"+'  ' + str(age) + '   ' +"years old,but")
print("it does not feel much different than being ")
print(str(age-1) + "." )
print("")
print("Sincerely,")
print("")
print(yourname)
